spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dselimovic1/ProjectHub.git
          searchPaths: 'config/{application}'
          username: lvrnjak1 # ${PROJECTHUB_GIT_USERNAME}
          password: 1lamsaetf # ${PROJECTHUB_GIT_PASSWORD}
  security:
    user:
      name: root
      password: secret

server:
  port: 8888
