spring:
  cloud:
    config:
      server:
        git:
          uri: ${HOME}/test-config
          searchPaths: 'config/{application}'
  security:
    user:
      name: root
      password: secret

server:
  port: 8888
