spring:
  datasource:
    url: ${TS_DATABASE_URL}
    username: projecthub
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    url: ${TS_DATABASE_URL}
    user: projecthub
    password: password
  rabbitmq:
    host: ${RABBITMQ_HOST}
    password: password
    username: projecthub
