spring:
  application:
    name: gateway-service

server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL}
  instance:
    preferIpAddress: true

ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 60000

zuul:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  routes:
    users:
      path: "/api/v1/users/**"
      serviceId: user-service
      stripPrefix: false
    token:
      path: "/oauth/token/**"
      serviceId: user-service
      stripPrefix: false
    tasks:
      path: "/api/v1/tasks/**"
      serviceId: task-service
      stripPrefix: false
    issues:
      path: "/api/v1/issues/**"
      serviceId: task-service
      stripPrefix: false
    priorites:
      path: "/api/v1/priorities"
      serviceId: task-service
      stripPrefix: false
    types:
      path: "/api/v1/types"
      serviceId: task-service
      stripPrefix: false
    statutes:
      path: "/api/v1/statuses"
      serviceId: task-service
      stripPrefix: false
    projects:
      path: "/api/v1/projects/**"
      serviceId: project-service
      stripPrefix: false
    notifications:
      path: "/api/v1/notifications/**"
      serviceId: notification-service
      stripPrefix: false
    subscriptions:
      path: "/api/v1/subscriptions/**"
      serviceId: notification-service
      stripPrefix: false
    emails:
      path: "/api/v1/emails/**"
      serviceId: email-service
      stripPrefix: false
    email-subscriptions:
      path: "/api/v1/email-subscriptions/**"
      serviceId: email-service
      stripPrefix: false
  sensitive-headers:
  ignored-patterns: "/api/v1/emails"