spring:
  application:
    name: gatewayservice

server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

zuul:
  routes:
    userservice: /api/v1/users/**
  ribbon:
    eager-load:
      enabled: true


