spring:
  application:
    name: gatewayservice

server:
  port: 8080


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    routes:
      enabled: true
    filters:
      enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

zuul:
  routes:
    users:
      path: "/api/v1/users/**"
      serviceId: userservice
  sensitive-headers:

