spring:
  datasource:
    url: jdbc:postgresql://email-service-db:5432/email-service-dev
    username: projecthub
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    url: jdbc:postgresql://email-service-db:5432/email-service-dev
    user: projecthub
    password: password
  mail:
    host: in-v3.mailjet.com
    port: 587
    username: f0daf554447d64120067f6f8d9c1a2bd
    password: 123658e6526109f8c5116167ff204819

eureka:
  instance:
    prefer-ip-address: true
    metadata-map:
      zone: zone1
  client:
    prefer-same-zone-eureka: true
    register-with-eureka: true
    fetch-registry: true
    region: region1
    service-url:
      zone1: http://discovery-server:8761/eureka/
    availability-zones:
      region1: zone1

mail:
  from: atlantic.project.hub@gmail.com