spring:
  datasource:
    url: jdbc:h2:mem:email-service-test
    username: projecthub
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  flyway:
    enabled: false

token:
  test:
    private-key: projecthub.jks
    password: projecthub
    alias: projecthub
