spring:
  datasource:
    url: ${DATABASE_URL}
    username: projecthub
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    url: ${DATABASE_URL}
    user: projecthub
    password: password
